Import('env')

Executable_Name = 'AFS'

Source_Files = [
				'main.c', 
				'board.c',
				'm_usb.c',
				'esp32.c',
				'motorapi.c',
				'rtcapi.c',
				'switch.c',
				'counterapi.c',
				'eepromapi.c',
				'ledapi.c'
				]

LibPath = []
Libs = []
CppPath = []

CppPath.append('#include')
LibPath.append("#lib")

# Linker expands it as "libavrdriverlib.a" 
Libs.append('avrdriverlib')

env.Append(CPPPATH=CppPath)
env.Append(LIBS=Libs)
env.Append(LIBPATH=LibPath)

program = env.createExecutable(executableName=Executable_Name, outputDirectory = '../build', sourceFiles = Source_Files)

programHex = env.createHexFile(hexName=Executable_Name, outputDirectory = '../build', elfFile=Executable_Name)
